# Generated by Django 3.1.2 on 2020-12-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='developers',
            name='skills',
            field=models.CharField(choices=[('Python', 'Python'), ('React', 'React'), ('Angular', 'Angular'), ('Redux', 'Redux'), ('Expert in css', 'Expert in css'), ('Graphic Design', 'Graphic Design'), ('Photo Editing', 'Photo Editing')], max_length=1000),
        ),
    ]
