# Generated by Django 3.1.2 on 2020-12-04 20:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201204_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('React', 'React'), ('Angular', 'Angular'), ('Redux', 'Redux'), ('Expert in css', 'Expert in css'), ('Graphic Design', 'Graphic Design'), ('Photo Editing', 'Photo Editing')], max_length=69),
        ),
    ]
