# Generated by Django 3.1.2 on 2020-12-04 21:28

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201204_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
