# Generated by Django 3.1.2 on 2020-12-05 13:47

from django.db import migrations, models
import multiselectfield.db.fields
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201205_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[register.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='developers',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('React', 'React'), ('Angular', 'Angular'), ('Redux', 'Redux'), ('Expert in css', 'Expert in css'), ('Graphic Design', 'Graphic Design'), ('Photo Editing', 'Photo Editing'), ('Firebase', 'Firebase')], max_length=78),
        ),
    ]
