# Generated by Django 3.1.2 on 2020-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceImageUrl',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
